# Quiz 1 Scratch Work

In [9]:
# 1.
# Question 1
# "What will be the output of the following code?

import re
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


In [4]:
# Assume a and b are two (20, 20) numpy arrays. The L2-distance (defined above) between two equal dimension arrays can be 
# calculated in python as follows:

import numpy as np

a = np.random.rand(20,20)
b = np.random.rand(20,20)

def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result 

In [ ]:
# Which of the following expressions using this function will produce a different result from the rest?

In [5]:
# A
l2_dist(a, b)

8.243948216572695

In [6]:
# B
l2_dist(np.reshape(a, (20 * 20)), np.reshape(b, (20 * 20, 1)))

162.31885040824307

In [7]:
# C
l2_dist(np.reshape(a, (20 * 20)), np.reshape(b, (20 * 20)))

8.243948216572695

In [8]:
# D
l2_dist(a.T, b.T)

8.243948216572695

In [ ]:
# The correct answer is B

In [10]:
# 3.
# Question 3
# Consider the following variables in Python:

a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)

In [ ]:
# Which of the following statements regarding these variables is correct?

In [11]:
# A
a4.ndim() == 1

TypeError: 'int' object is not callable

In [13]:
# B
a1.shape == a2.shape

False

In [14]:
# C
a5.shape == a1.shape

True

In [15]:
# D
a3.shape == a4.shape

False

In [ ]:
# C is the correct answer

In [16]:
# Question 4
# Which of the following is the correct output for the code given below?

import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


In [17]:
# 5.
# Question 5
# Given the 6x6 NumPy array r shown below, which of the following options would slice the array to produce the output:
#     array([[14, 15],
#            [20, 21]])

r = np.array([[0,1,2,3,4,5],[6,7,8,9,10,11],[12,13,14,15,16,17],[18,19,20,21,22,23],[24,25,26,27,28,29],[30,31,32,33,34,35]])
print(r)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [18]:
# A
r[2:3,2:3]

array([[14]])

In [19]:
# B
r[[2,3],[2,3]]

array([14, 21])

In [20]:
# C
r[[2,4],[2,4]]

array([14, 28])

In [21]:
# D
r[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [22]:
# Question 6
import re 
s = 'ACBCAC'
# For the given string, which of the following regular expressions can be used to check if the string starts with 'AC'?

In [23]:
# A
re.findall('AC', s)

['AC', 'AC']

In [24]:
# B
re.findall('^[AC]', s)

['A']

In [25]:
# C
re.findall('[^A]C', s)

['BC']

In [26]:
# D
re.findall('^AC', s)

['AC']

In [28]:
# Question 7
# What will be the output of the variable L after the following code is executed?

import re
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)

print(L) # addition to find the length of L

5


In [29]:
# 8.
# Question 8
# Which of the following is the correct regular expression to extract all the phone numbers from the following chunk of text:

d = 'Office of Research Administration: (734) 647-6333 | 4325 North Quad Office of Budget and Financial Administration: (734) 647-8044 | 309 Maynard, Suite 205 Health Informatics Program: (734) 763-2285 | 333 Maynard, Suite 500 Office of the Dean: (734) 647-3576 | 4322 North Quad UMSI Engagement Center: (734) 763-1251 | 777 North University Faculty Adminstrative Support Staff: (734) 764-9376 | 4322 North Quad"

[(]\d{3}[)]\s\d{3}[-]\d{4}

SyntaxError: EOL while scanning string literal (3099540141.py, line 5)

In [30]:

\d{3}[-]\d{3}[-]\d{4}

SyntaxError: unexpected character after line continuation character (2254406212.py, line 1)

In [31]:
text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''

import re
pattern = (.)
print(len(re.findall(pattern,text)))

SyntaxError: invalid syntax (791638465.py, line 8)

In [32]:
text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''

import re
pattern = '[a-d]'
print(len(re.findall(pattern,text)))

40


In [33]:
text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''

import re
pattern = 'freedom'
print(len(re.findall(pattern,text)))

6


In [34]:
text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''

import re
pattern = \(.\) 
print(len(re.findall(pattern,text)))

SyntaxError: unexpected character after line continuation character (1600054509.py, line 8)